# ------------------------------------------------------------
# ---                  kitty config file                   ---
# ------------------------------------------------------------


# -- Websites
# ---------------------------
"youtube" = "ó°—ƒ"
"twitch" = "ó°•ƒ"
"gitlab" = "ó°® "
"github" = "ó°Š¤"
"git" = "ó°Š¢"
"google" = "ó°Š­"


# -- File formats
# ---------------------------
".html" = "ó°Œ"
".cpp" = "ó°™²"
".lua" = "ó°¢±"
".css" = "ó°Œœ"
".pdf" = "î««"
".jpg" = "ó°ˆ¥"
".png" = "ó°¸­"
".mkv" = "ó°ˆ«"
".mp4" = "ó°ˆ«"
".py" = "ó°Œ "
".md" = "ó°”"
".m" = "ó°˜¨"


# -- Multimedia
# ---------------------------
"feh" = "ó°‹©"
"mpv" = "ï®"
"spotify" = "ó°“‡"


# -- Browsers
# ---------------------------
"firefox" = "ó°ˆ¹"
"chrome" = "ó°Š¯"
"chromium" = "ó°Š¯"


# -- System
# ---------------------------
"nemo" = "ó°°"
"kitty" = "î•"
"pavucontrol" = "ó±Ÿ›"


# -- Applications
# ---------------------------
"libreoffice calc" = "ó±"
"libreoffice writer" = "ó±’"
"libreoffice" = "ó°†"
"zotero" = "ó°‚º"
"thunderbird" = "ï°"
"qbittorrent" = "ó°›´"
"discord" = "ó°™¯"
"picard" = "ó°ˆ£"
"filelight" = "ó°ƒ¢"
"steam" = "ó°““"
"lutris" = "ó°Š—"
"epicgameslauncher.exe" = "ó°Š—"
"vim" = "îŸ…"
"code" = "îœŒ"
"matlab" = "ó°˜¨"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
