# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

# System
"nemo" = "ó°°"
"kitty" = "î•"

# Websites
"youtube" = "ó°—ƒ"
"twitch" = "ó°•ƒ"
"gitlab" = "ó°® "
"github" = "ó°Š¤"
"git" = "ó°Š¢"
"google" = "ó°Š­"

# File formats
".py" = "ó°Œ "
".cpp" = "ó°™²"
".lua" = "ó°¢±"
".md" = "ó°”"
".html" = "ó°Œ"
".css" = "ó°Œœ"
".pdf" = "î««"
".jpg" = "ó°ˆ¥"
".png" = "ó°¸­"
".mkv" = "ó°ˆ«"
".mp4" = "ó°ˆ«"
".m" = "ó°˜¨"

# Coding
"nvim" = "îŸ…"
"code" = "îœŒ"
"matlab" = "ó°˜¨"

# Multimedia
"feh" = "ó°‹©"
"mpv" = "ï®"
"spotify" = "ó°“‡"

# Browsers
"firefox" = "ó°ˆ¹"
"chrome" = "ó°Š¯"
"chromium" = "ó°Š¯"

# Applications
"libreoffice calc" = "ó±"
"libreoffice writer" = "ó±’"
"libreoffice" = "ó°†"
"zotero" = "ó°‚º"
"thunderbird" = "ï°"
"qbittorrent" = "ó°›´"
"discord" = "ó°™¯"
"picard" = "ó°ˆ£"
"filelight" = "ó°ƒ¢"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
